{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "auth-service.fullname" . }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "auth-service.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "auth-service.name" . }}
        {{- if .Values.networkPolicy.ingressNamespaceSelector }}
        - namespaceSelector:
            matchLabels:
              {{- toYaml .Values.networkPolicy.ingressNamespaceSelector | nindent 14 }}
        {{- end }}
      ports:
        - protocol: TCP
          port: {{ .Values.service.targetPort }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: {{ include "auth-service.name" . }}
              app.kubernetes.io/component: postgresql
      ports:
        - protocol: TCP
          port: {{ .Values.postgresql.service.port }}
    {{- if .Values.networkPolicy.allowExternal }}
    - to:
        - ipBlock:
            cidr: 0.0.0.0/0
            {{- if .Values.networkPolicy.externalCIDRs }}
            except:
              {{- toYaml .Values.networkPolicy.externalCIDRs | nindent 14 }}
            {{- end }}
    {{- end }}
{{- end }}