apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name }}
  labels:
    {{- include "auth-service.labels" . | nindent 4 }}
type: Opaque
data:
  # These values should be overridden in a production environment
  # using proper secret management
  
  # Database credentials
  POSTGRES_USER: {{ .Values.postgresql.auth.username | default "postgres" | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.auth.password | default "postgres" | b64enc | quote }}
  
  # Security settings
  SECRET_KEY: {{ .Values.application.secretKey | default "supersecretkey1234567890abcdefghijklmnopqrstuvwxyz" | b64enc | quote }}
  
  # Email credentials
  SMTP_USER: {{ .Values.application.email.smtpUser | default "" | b64enc | quote }}
  SMTP_PASSWORD: {{ .Values.application.email.smtpPassword | default "" | b64enc | quote }}
  
  # Superuser credentials
  FIRST_SUPERUSER: {{ .Values.application.firstSuperuser | default "admin@example.com" | b64enc | quote }}
  FIRST_SUPERUSER_PASSWORD: {{ .Values.application.firstSuperuserPassword | default "admin123" | b64enc | quote }}