apiVersion: v2
name: auth-service
description: A Helm chart for Authentication Management Component using FastAPI
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - authentication
  - fastapi
  - jwt
maintainers:
  - name: DevOps Team
    email: devops@example.com