apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: ${DOCKER_REGISTRY}/auth-server-fastapi:${IMAGE_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "200m"
            memory: "256Mi"
        env:
          - name: POSTGRES_SERVER
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: POSTGRES_SERVER
          - name: POSTGRES_PORT
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: POSTGRES_PORT
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: auth-server-secrets
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-server-secrets
                key: POSTGRES_PASSWORD
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: auth-server-secrets
                key: SECRET_KEY
          - name: ACCESS_TOKEN_EXPIRE_MINUTES
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: ACCESS_TOKEN_EXPIRE_MINUTES
          - name: REFRESH_TOKEN_EXPIRE_DAYS
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: REFRESH_TOKEN_EXPIRE_DAYS
          - name: BACKEND_CORS_ORIGINS
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: BACKEND_CORS_ORIGINS
          - name: SMTP_HOST
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: SMTP_HOST
                optional: true
          - name: SMTP_PORT
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: SMTP_PORT
                optional: true
          - name: SMTP_USER
            valueFrom:
              secretKeyRef:
                name: auth-server-secrets
                key: SMTP_USER
                optional: true
          - name: SMTP_PASSWORD
            valueFrom:
              secretKeyRef:
                name: auth-server-secrets
                key: SMTP_PASSWORD
                optional: true
          - name: EMAILS_FROM_EMAIL
            valueFrom:
              configMapKeyRef:
                name: auth-server-config
                key: EMAILS_FROM_EMAIL
                optional: true
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
      terminationGracePeriodSeconds: 30