apiVersion: v1
kind: Secret
metadata:
  name: auth-server-secrets
  labels:
    app: auth-server
type: Opaque
data:
  # Database credentials
  # Note: These are example values. In production, use proper secret management.
  # Values are base64 encoded
  POSTGRES_USER: cG9zdGdyZXM=  # postgres
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  
  # Security settings
  SECRET_KEY: c3VwZXJzZWNyZXRrZXkxMjM0NTY3ODkwYWJjZGVmZ2hpamtsbW5vcHFyc3R1dnd4eXo=  # example key
  
  # Email credentials
  SMTP_USER: bm9yZXBseUBleGFtcGxlLmNvbQ==  # noreply@example.com
  SMTP_PASSWORD: ZXhhbXBsZXBhc3N3b3Jk  # examplepassword
  
  # Superuser credentials
  FIRST_SUPERUSER: YWRtaW5AZXhhbXBsZS5jb20=  # admin@example.com
  FIRST_SUPERUSER_PASSWORD: YWRtaW4xMjM=  # admin123